info:
  version: 0.0.1
  methods:
    - ping
    - info
    - list
    - search
  link: https://github.com/Slowhand0309/MichiEki
gen_urls:
  - http://www.seaview.jp/rs/101-111.htm
  - http://www.seaview.jp/rs/102-111.htm
  - http://www.seaview.jp/rs/103-111.htm
  - http://www.seaview.jp/rs/104-111.htm
  - http://www.seaview.jp/rs/105-111.htm
  - http://www.seaview.jp/rs/106-111.htm
  - http://www.seaview.jp/rs/107-111.htm
  - http://www.seaview.jp/rs/108-111.htm
  - http://www.seaview.jp/rs/109-111.htm
  - http://www.seaview.jp/rs/110-111.htm
geo_address:
  北海道: 札幌市中央区北3条西6丁目
  青森県: 青森市長島一丁目1-1
  岩手県: 盛岡市内丸10番1号
  宮城県: 仙台市青葉区本町3丁目8番1号
  秋田県: 秋田市山王四丁目１－１
  山形県: 山形市松波二丁目8－1
  福島県: 福島市杉妻町2-16
  茨城県: 水戸市笠原町978番6
  栃木県: 宇都宮市塙田1-1-20
  群馬県: 前橋市大手町1-1-1
  埼玉県: さいたま市浦和区高砂3-15-1
  千葉県: 千葉市中央区市場町1番1号
  東京都: 新宿区西新宿2-8-1
  神奈川県: 横浜市中区日本大通1
  新潟県: 新潟市中央区新光町4番地1
  富山県: 富山市新総曲輪1番7号
  石川県: 金沢市鞍月1丁目1番地
  福井県: 福井市大手３丁目17番1号
  山梨県: 甲府市丸の内1-6-1
  長野県: 長野市大字南長野字幅下692-2
  岐阜県: 岐阜市薮田南2丁目1番1号
  静岡県: 静岡市葵区追手町9番6号
  愛知県: 名古屋市中区三の丸三丁目1番2号
  三重県: 津市広明町13番地
  滋賀県: 大津市京町四丁目1番1号
  京都府: 京都市上京区下立売通新町西入薮ノ内町
  大阪府: 大阪市中央区大手前2丁目
  兵庫県: 神戸市中央区下山手通5丁目10番1号
  奈良県: 奈良市登大路町30
  和歌山県: 和歌山市小松原通1-1
  鳥取県: 鳥取市東町1丁目220
  島根県: 松江市殿町１番地
  岡山県: 岡山市北区内山下２丁目４番６号
  広島県: 広島市中区基町10-52
  山口県: 山口市滝町1番1号
  徳島県: 徳島市万代町1丁目1番地
  香川県: 高松市番町四丁目1番10号
  愛媛県: 松山市一番町4丁目4-2
  高知県: 高知市丸ノ内1丁目2番20号
  福岡県: 福岡市博多区東公園7番7号
  佐賀県: 佐賀市城内1丁目1-59
  長崎県: 長崎市江戸町2-13
  熊本県: 熊本市中央区水前寺6丁目18番1号
  大分県: 大分市大手町3丁目1番1号
  宮崎県: 宮崎市橘通東二丁目10番1号
  鹿児島県: 鹿児島市鴨池新町10番1号
  沖縄県: 那覇市泉崎1-2-2
